### ISSUE TITLE
Performance bottleneck

### ISSUE THREAD

**Issue by YeskaNova** [cheton/flattree#5]
Hi,

Thank you for the awesome infinit-tree library. When I try to load 80k+ nodes under a single node, this line incredibly slows down the loading :

https://github.com/cheton/flattree/blob/6b0f5163f647014cb232f615c6427f6caa0817b9/src/flatten.js#L123

I think you can change this line with a less expensive check : 
`if(index === current.children.length-1)`

I gained 1.4 seconds with this. Can you confirm that I didn't break something ? It seems to me that the original check does a long roundtrip to just do that simple check.

Thank you,

Yassine

**Comment by cheton** [comment]
That's a good point. This change will definitely reduce the time for searching the array for the specified node. Thank you for the finding.

**Comment by YeskaNova** [comment]
Thank you.

**Comment by cheton** [comment]
Just published [0.11.1](https://github.com/cheton/flattree/releases/tag/v0.11.1) to address the performance issue.
